{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_failure():\n        \"\"\"this test fails\"\"\"\n>       assert False\nE       assert False\n\n02test_Allure2.py:15: AssertionError"}, "description": "this test fails", "start": 1638072949034, "stop": 1638072949034, "uuid": "7e061818-ecf7-4cb6-b01a-fd5e50a25c8f", "historyId": "9f9f0d3790b587ede96e0a1bbf7e2747", "testCaseId": "9e2d16fd58ed55336d9129332ee9407c", "fullName": "02test_Allure2#test_failure", "labels": [{"name": "suite", "value": "02test_Allure2"}, {"name": "host", "value": "huixdeMacBook-Pro.local"}, {"name": "thread", "value": "1910-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "02test_Allure2"}]}